spring:
    datasource:
        driverClassName: org.h2.Driver
        password:
        url: jdbc:h2:mem:auth-forum
        username: sa

    h2:
        console:
            enabled: true
            path: /h2-console

jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}